export const AuthConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const AppointmentConstants = {
  ADD_APPOINTMENT_REQUEST: "ADD_APPOINTMENT_REQUEST",
  ADD_APPOINTMENT_SUCCESS: "ADD_APPOINTMENT_SUCCESS",
  ADD_APPOINTMENT_FAILURE: "ADD_APPOINTMENT_FAILURE",

  GET_APPOINTMENT_REQUEST: "GET_APPOINTMENT_REQUEST",
  GET_APPOINTMENT_SUCCESS: "GET_APPOINTMENT_SUCCESS",
  GET_APPOINTMENT_FAILURE: "GET_APPOINTMENT_FAILURE",
};

export const DentalCheckupConstants = {
  ADD_DENTALCHECKUP_REQUEST: "ADD_DENTALCHECKUP_REQUEST",
  ADD_DENTALCHECKUP_SUCCESS: "ADD_DENTALCHECKUP_SUCCESS",
  ADD_DENTALCHECKUP_FAILURE: "ADD_DENTALCHECKUP_FAILURE",

  GET_DENTALCHECKUP_REQUEST: "GET_DENTALCHECKUP_REQUEST",
  GET_DENTALCHECKUP_SUCCESS: "GET_DENTALCHECKUP_SUCCESS",
  GET_DENTALCHECKUP_FAILURE: "GET_DENTALCHECKUP_FAILURE",
};


export const DoctorConstants={
  GET_DOCTOR_REQUEST:"GET_DOCTOR_REQUEST",
  GET_DOCTOR_SUCCESS:"GET_DOCTOR_SUCCESS",
  GET_DOCTOR_FAILURE:"GET_DOCTOR_FAILURE",
 }