export const AuthConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const AppointmentConstants = {
  ADD_APPOINTMENT_REQUEST: "ADD_APPOINTMENT_REQUEST",
  ADD_APPOINTMENT_SUCCESS: "ADD_APPOINTMENT_SUCCESS",
  ADD_APPOINTMENT_FAILURE: "ADD_APPOINTMENT_FAILURE",

  GET_APPOINTMENT_REQUEST: "GET_APPOINTMENT_REQUEST",
  GET_APPOINTMENT_SUCCESS: "GET_APPOINTMENT_SUCCESS",
  GET_APPOINTMENT_FAILURE: "GET_APPOINTMENT_FAILURE",
};

export const DentalCheckupConstants = {
  GET_CHECKUP_REQUEST: "GET_CHECKUP_REQUEST",
  GET_CHECKUP_SUCCESS: "GET_CHECKUP_SUCCESS",
  GET_CHECKUP_FAILURE: "GET_CHECKUP_FAILURE",
};


export const DoctorConstants={
  GET_DOCTOR_REQUEST:"GET_DOCTOR_REQUEST",
  GET_DOCTOR_SUCCESS:"GET_DOCTOR_SUCCESS",
  GET_DOCTOR_FAILURE:"GET_DOCTOR_FAILURE",

  DOCTOR_PROFILE_REQUEST:"DOCTOR_PROFILE_REQUEST",
  DOCTOR_PROFILE_SUCCESS:"DOCTOR_PROFILE_SUCCESS",
  DOCTOR_PROFILE_FAILURE:"DOCTOR_PROFILE_FAILURE",
 }


 export const CheckupAppointmentConstants={
  ADD_CHECKUPAPPOINTMENT_REQUEST:"ADD_CHECKUPAPPOINTMENT_REQUEST",
  ADD_CHECKUPAPPOINTMENT_SUCCESS:"ADD_CHECKUPAPPOINTMENT_SUCCESS",
  ADD_CHECKUPAPPOINTMENT_FAILURE:"ADD_CHECKUPAPPOINTMENT_FAILURE",

  GET_CHECKUPAPPOINTMENT_REQUEST:"GET_CHECKUPAPPOINTMENT_REQUEST",
  GET_CHECKUPAPPOINTMENT_SUCCESS:"GET_CHECKUPAPPOINTMENT_SUCCESS",
  GET_CHECKUPAPPOINTMENT_FAILURE:"GET_CHECKUPAPPOINTMENT_FAILURE",
 }



 export const SearchAppointmentConstants={
  SEARCH_APPOINTMENT_REQUEST:"SEARCH_APPOINTMENT_REQUEST",
  SEARCH_APPOINTMENT_SUCCESS:"SEARCH_APPOINTMENT_SUCCESS",
  SEARCH_APPOINTMENT_FAILURE:"SEARCH_APPOINTMENT_FAILURE",
 }